# Generated by Django 4.2.6 on 2023-10-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ManyToManyField(blank=True, to='blog.image'),
        ),
    ]
