# Generated by Django 4.2.6 on 2023-10-19 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_services_trainerservices_mentaltrainerservices_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentaltrainerservices',
            name='services_ptr',
        ),
        migrations.RemoveField(
            model_name='mentaltrainerservices',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='trainerservices',
            name='services_ptr',
        ),
        migrations.RemoveField(
            model_name='trainerservices',
            name='trainer',
        ),
        migrations.DeleteModel(
            name='DieticianServices',
        ),
        migrations.DeleteModel(
            name='MentalTrainerServices',
        ),
        migrations.DeleteModel(
            name='Services',
        ),
        migrations.DeleteModel(
            name='TrainerServices',
        ),
    ]
