# Generated by Django 4.2.7 on 2023-11-06 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gym', '0004_trainer_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dietitian',
            fields=[
                ('trainer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gym.trainer')),
            ],
            options={
                'verbose_name': 'Dietetyk',
                'verbose_name_plural': 'Dietetycy',
            },
            bases=('gym.trainer',),
        ),
        migrations.CreateModel(
            name='DietitianServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MentalTrainer',
            fields=[
                ('trainer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gym.trainer')),
            ],
            options={
                'verbose_name': 'Trener mentalny',
                'verbose_name_plural': 'Trenerzy mentalni',
            },
            bases=('gym.trainer',),
        ),
        migrations.CreateModel(
            name='MentalTrainerServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='MentalTrainerAppointment',
            fields=[
                ('appointment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gym.appointment')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.mentaltrainerservices')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.mentaltrainer')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('gym.appointment',),
        ),
        migrations.CreateModel(
            name='DietitianAppointment',
            fields=[
                ('appointment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gym.appointment')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.dietitianservices')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.dietitian')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('gym.appointment',),
        ),
    ]
