# Generated by Django 4.2.6 on 2023-10-19 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_dieticianservices_mentaltrainerservices_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('hour', models.CharField(choices=[('07:00', '07:00'), ('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00'), ('22:00', '22:00'), ('23:00', '23:00')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainerAppointment',
            fields=[
                ('appointment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gym.appointment')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.trainerservices')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.trainer')),
            ],
            options={
                'abstract': False,
            },
            bases=('gym.appointment',),
        ),
        migrations.CreateModel(
            name='MentalTrainerAppointment',
            fields=[
                ('appointment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gym.appointment')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.mentaltrainerservices')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.mentaltrainer')),
            ],
            options={
                'abstract': False,
            },
            bases=('gym.appointment',),
        ),
        migrations.CreateModel(
            name='DieticianAppointment',
            fields=[
                ('appointment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='gym.appointment')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.dieticianservices')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.dietician')),
            ],
            options={
                'abstract': False,
            },
            bases=('gym.appointment',),
        ),
    ]
