# Generated by Django 4.2.6 on 2023-10-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_trainerappointment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerappointment',
            name='user',
        ),
    ]
