# Generated by Django 4.2.6 on 2023-10-25 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_trainerappointment_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('07:00', '07:00'), ('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00'), ('22:00', '22:00'), ('23:00', '23:00')], max_length=10, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='hour',
        ),
        migrations.AddField(
            model_name='appointment',
            name='chosen_hour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.workinghour'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='working_hours',
            field=models.ManyToManyField(null=True, related_name='trainers', to='gym.workinghour'),
        ),
    ]
