# Generated by Django 4.2.6 on 2023-10-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0011_alter_workinghour_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='workinghour',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
