# Generated by Django 4.2.6 on 2023-10-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0012_workinghour_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='chosen_hour',
        ),
        migrations.AddField(
            model_name='appointment',
            name='chosen_hour',
            field=models.ManyToManyField(null=True, to='gym.workinghour'),
        ),
    ]
