# Generated by Django 4.2.6 on 2023-10-25 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0013_remove_appointment_chosen_hour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='chosen_hour',
        ),
        migrations.AddField(
            model_name='appointment',
            name='chosen_hour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gym.workinghour'),
        ),
    ]
