# Generated by Django 4.2.6 on 2023-10-27 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0014_remove_appointment_chosen_hour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dieticianappointment',
            name='appointment_ptr',
        ),
        migrations.RemoveField(
            model_name='dieticianappointment',
            name='services',
        ),
        migrations.RemoveField(
            model_name='dieticianappointment',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='mentaltrainer',
            name='mental_trainer',
        ),
        migrations.RemoveField(
            model_name='mentaltrainerappointment',
            name='appointment_ptr',
        ),
        migrations.RemoveField(
            model_name='mentaltrainerappointment',
            name='services',
        ),
        migrations.RemoveField(
            model_name='mentaltrainerappointment',
            name='trainer',
        ),
        migrations.DeleteModel(
            name='Dietician',
        ),
        migrations.DeleteModel(
            name='DieticianAppointment',
        ),
        migrations.DeleteModel(
            name='DieticianServices',
        ),
        migrations.DeleteModel(
            name='MentalTrainer',
        ),
        migrations.DeleteModel(
            name='MentalTrainerAppointment',
        ),
        migrations.DeleteModel(
            name='MentalTrainerServices',
        ),
    ]
